steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/cloudside-academy/test-nav-repo/my-app:$SHORT_SHA', '.'
    ]

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-central1-docker.pkg.dev/cloudside-academy/test-nav-repo/my-app:$SHORT_SHA'
    ]

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-cloud-run-function
      - --region=us-central1
      - --gen2
      - --runtime=nodejs20
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point=YOUR_FUNCTION_NAME
      - --source=us-central1-docker.pkg.dev/cloudside-academy/test-nav-repo/cloud-run-function
      - --memory=512MB
      - --timeout=60s
      - --max-instances=3
      
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/cloudside-academy/test-nav-repo/my-app:$SHORT_SHA'
