# Build and tag usiing sha

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/cloudside-academy/github.com/naveenrayapati/cloudbuild:${COMMIT_SHA}', '-f', 'Dockerfile']


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudside-academy/github.com/naveenrayapati/cloudbuild:${COMMIT_SHA}']
# Create release in Google Cloud Deploy


- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "gitops",
      "--region", "asia-south1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "cloudbuild=gcr.io/cloudside-academy/github.com/naveenrayapati/cloudbuild:${COMMIT_SHA}"
    ]
