apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gitops
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
---

#Our 1st Cluster TARGET
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster:  projects/cloudside-academy/locations/asia-south1-a/clusters/cluster-1
